#!/usr/bin/env python3
"""
Video Transcribe Skill
Transcribe YouTube videos using yt-dlp + Whisper
Extracts cookies directly from Chrome on Linux
"""

import argparse
import os
import sqlite3
import subprocess
import sys
import time
from pathlib import Path
from urllib.parse import urlparse

def find_chrome_cookies():
    """Find Chrome cookies file."""
    paths = [
        os.path.expanduser("~/.config/google-chrome/Default/Cookies"),
        os.path.expanduser("~/.config/chromium/Default/Cookies"),
        os.path.expanduser("~/.config/google-chrome-beta/Default/Cookies"),
    ]
    for path in paths:
        if os.path.exists(path):
            return path
    return None

def extract_youtube_cookies(cookies_file):
    """Extract YouTube cookies from Chrome SQLite database."""
    try:
        conn = sqlite3.connect(cookies_file)
        cursor = conn.cursor()
        
        # YouTube cookies are typically on .youtube.com
        cursor.execute("""
            SELECT name, value, host_key, path, expires_utc, is_secure, is_httponly
            FROM cookies 
            WHERE host_key LIKE '%youtube%'
        """)
        
        cookies = []
        for row in cursor.fetchall():
            cookies.append({
                'name': row[0],
                'value': row[1],
                'domain': row[2],
                'path': row[3],
                'expires': row[4],
                'secure': row[5],
                'http_only': row[6]
            })
        
        conn.close()
        return cookies
    except Exception as e:
        print(f"Error reading cookies: {e}")
        return []

def write_netscape_cookies(cookies, output_file):
    """Write cookies in Netscape format for yt-dlp."""
    try:
        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by video-transcribe skill\n\n")
            
            for cookie in cookies:
                # Convert Chrome's host_key to proper domain format
                domain = cookie['domain']
                if domain.startswith('.'):
                    domain = domain[1:]
                
                # Convert expires_utc (WebKit format) to timestamp
                expires = int(cookie['expires']) if cookie['expires'] > 0 else 0
                
                # Netscape format: domain, flag, path, secure, expiration, name, value
                f.write(f"{domain}\tTRUE\t{cookie['path']}\t{str(cookie['secure']).upper()}\t{expires}\t{cookie['name']}\t{cookie['value']}\n")
        
        return output_file
    except Exception as e:
        print(f"Error writing cookies: {e}")
        return None

def check_chrome():
    """Check if Chrome is installed."""
    result = subprocess.run(
        ["which", "google-chrome"],
        capture_output=True, text=True
    )
    return result.returncode == 0

def download_audio_yt_dlp(url, cookies_file=None):
    """Download audio from YouTube using yt-dlp."""
    output_file = "/tmp/video_audio.mp3"
    
    cmd = [
        "yt-dlp",
        "-x",  # Extract audio
        "--audio-format", "mp3",
        "-o", output_file,
        "--no-playlist",
        "--quiet",
        "--user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36"
    ]
    
    # Only add cookies if we have a valid file
    if cookies_file and os.path.exists(cookies_file):
        cmd.extend(["--cookies", cookies_file])
    
    # Add URL at the end
    cmd.append(url)
    
    print(f"📥 Downloading audio from: {url}")
    
    if cookies_file:
        print(f"   Using cookies: {cookies_file}")
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        error_msg = result.stderr.strip()
        print(f"Error: {error_msg}")
        
        if "Sign in to confirm" in error_msg:
            print("\n⚠️ YouTube is blocking downloads")
            print("   Authentication required - try signing into YouTube in browser first")
        return None
    
    if os.path.exists(output_file):
        print(f"✓ Audio downloaded: {output_file}")
        return output_file
    
    return None

def transcribe_audio(audio_file, model="turbo", output_format="txt"):
    """Transcribe audio using Whisper."""
    output_dir = "/tmp/transcripts"
    Path(output_dir).mkdir(exist_ok=True)
    
    base_name = os.path.splitext(os.path.basename(audio_file))[0]
    
    print(f"🎙️ Transcribing with Whisper ({model})...")
    
    cmd = [
        "whisper",
        audio_file,
        "--model", model,
        "--output_format", output_format,
        "--output_dir", output_dir,
        "--no_timestamps"
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"Error: {result.stderr}")
        return None
    
    ext = f".{output_format}"
    transcript_file = os.path.join(output_dir, base_name + ext)
    
    if os.path.exists(transcript_file):
        return transcript_file
    
    txt_file = os.path.join(output_dir, base_name + ".txt")
    if os.path.exists(txt_file):
        return txt_file
    
    return None

def read_transcript(file_path):
    """Read transcript file."""
    with open(file_path, 'r') as f:
        return f.read()

def main():
    parser = argparse.ArgumentParser(
        description="🎬 Transcribe YouTube videos",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  video-transcribe "https://youtu.be/2KWhHY0KTMk"
  video-transcribe "URL" --model medium --format srt
  video-transcribe --check  # Check system status
        """
    )
    parser.add_argument("url", nargs="?", help="YouTube video URL")
    parser.add_argument("--model", default="turbo",
                       choices=["tiny", "base", "small", "medium", "large", "turbo"],
                       help="Whisper model size")
    parser.add_argument("--format", default="txt",
                       choices=["txt", "srt", "vtt", "json"],
                       help="Output format")
    parser.add_argument("--check", action="store_true",
                       help="Check Chrome and cookies status")
    parser.add_argument("--cookies", 
                       help="Path to cookies file (Netscape format)")
    
    args = parser.parse_args()
    
    if args.check:
        print("\n🎬 Video Transcribe Skill - System Check")
        print("="*50)
        
        chrome_ok = check_chrome()
        print(f"Chrome: {'✓ Installed' if chrome_ok else '✗ Not found'}")
        
        cookies_file = find_chrome_cookies()
        if cookies_file:
            print(f"Chrome Cookies: ✓ {cookies_file}")
            # Count YouTube cookies
            try:
                conn = sqlite3.connect(cookies_file)
                cursor = conn.cursor()
                cursor.execute("SELECT COUNT(*) FROM cookies WHERE host_key LIKE '%youtube%'")
                count = cursor.fetchone()[0]
                conn.close()
                print(f"   YouTube cookies: {count}")
            except:
                pass
        else:
            print("Chrome Cookies: ✗ Not found")
            print("   Sign into YouTube in Chrome to generate cookies")
        
        print("="*50)
        sys.exit(0)
    
    if not args.url:
        parser.print_help()
        sys.exit(1)
    
    print(f"\n🎬 Video Transcribe Skill")
    print(f"URL: {args.url}")
    print(f"Model: {args.model}")
    print(f"Format: {args.format}\n")
    
    # Check Chrome
    if not check_chrome():
        print("⚠️ Chrome not found - install with: apt-get install google-chrome-stable")
        sys.exit(1)
    
    # Try to use Chrome cookies
    cookies_file = None
    
    if args.cookies:
        # User provided cookies file
        cookies_file = args.cookies
        print(f"✓ Using provided cookies: {cookies_file}")
    else:
        # Try to extract from Chrome
        chrome_cookies = find_chrome_cookies()
        if chrome_cookies:
            print(f"✓ Found Chrome cookies: {chrome_cookies}")
            
            # Extract YouTube cookies
            yt_cookies = extract_youtube_cookies(chrome_cookies)
            if yt_cookies:
                netscape_file = "/tmp/youtube_cookies.txt"
                if write_netscape_cookies(yt_cookies, netscape_file):
                    cookies_file = netscape_file
                    print(f"   Extracted {len(yt_cookies)} YouTube cookies")
            else:
                print("   No YouTube cookies found - sign into YouTube in Chrome first")
        else:
            print("⚠️ No Chrome cookies found")
    
    # Download audio
    audio_file = download_audio_yt_dlp(args.url, cookies_file)
    
    if not audio_file:
        print("\n❌ Failed to download audio")
        print("\n📋 To get YouTube working:")
        print("   1. Install Chrome: apt-get install google-chrome-stable")
        print("   2. Sign into YouTube in Chrome")
        print("   3. Wait for cookies to be saved")
        print("   4. Run: video-transcribe --check")
        sys.exit(1)
    
    # Transcribe
    transcript_file = transcribe_audio(audio_file, args.model, args.format)
    
    if not transcript_file:
        print("❌ Failed to transcribe audio")
        sys.exit(1)
    
    # Print transcript
    content = read_transcript(transcript_file)
    print("\n" + "="*60)
    print("TRANSCRIPT:")
    print("="*60)
    print(content[:5000] if len(content) > 5000 else content)
    print("="*60)
    print(f"\n✓ Full transcript saved to: {transcript_file}")
    print(f"  ({len(content)} characters)")

if __name__ == "__main__":
    main()
